"use client"
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'

import StyledComponentsRegistry from '../styles/lib/registry';

import store from '@/redux/store';

import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'upwork',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Provider store={store}>
              {children}
          </Provider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
